trigger:
- master

pool:
  vmImage: default

steps:
- script: |
    echo "Setting MAVEN_HOME"
    echo "##vso[task.setvariable variable=MAVEN_HOME]/usr/share/maven"
    echo "Adding Maven bin to PATH"
    echo "##vso[task.prependpath]$(MAVEN_HOME)/bin"
  displayName: 'Set MAVEN_HOME and add to PATH'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
